spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      batch:
        jdbc-url: jdbc:mysql://localhost:3306/batch
        username: batch
        password: batch
        driver-class-name: com.mysql.cj.jdbc.Driver

      application:
        jdbc-url: jdbc:mysql://localhost:3306/application
        username: application
        password: application
        driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    jdbc:
      initialize-schema: always
    job:
      names: ${job.name:NONE}


logging:
  level:
   org:
     springframework:
       batch: DEBUG
